builds:
  - binary: check-postqueue
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/sugy/check-postqueue/lib.version={{.Version}}
      - -X github.com/sugy/check-postqueue/lib.commit={{.ShortCommit}}
      - -X github.com/sugy/check-postqueue/lib.date={{.Date}}
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: sugy
    name: check-postqueue
